-- 创建内镜表 (scope)
CREATE TABLE scope (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  no VARCHAR(50) NOT NULL COMMENT '内镜序号',
  name VARCHAR(100) NOT NULL COMMENT '内镜名称',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='内镜表';

-- 创建消毒设备类型表 (device_type)
CREATE TABLE device_type (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  name VARCHAR(100) NOT NULL COMMENT '类型名称',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消毒设备类型表';

-- 创建员工表 (staff)
CREATE TABLE staff (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  no VARCHAR(50) NOT NULL COMMENT '工号',
  name VARCHAR(100) NOT NULL COMMENT '姓名',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工表';

-- 创建消毒设备表 (device)
CREATE TABLE device (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  no VARCHAR(50) NOT NULL COMMENT '设备序号',
  name VARCHAR(100) NOT NULL COMMENT '设备名称',
  type_id BIGINT NOT NULL COMMENT '设备类型ID',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消毒设备表';

-- 创建日志表 (log)
CREATE TABLE log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  staff_no VARCHAR(50) NOT NULL COMMENT '员工工号',
  time DATETIME NOT NULL COMMENT '时间',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日志表';

-- 创建子日志表 (sub_log)
CREATE TABLE sub_log (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
  log_id BIGINT NOT NULL COMMENT '日志ID',
  scope_no VARCHAR(50) NOT NULL COMMENT '内镜序号',
  device_no VARCHAR(50) NOT NULL COMMENT '设备序号',
  time DATETIME NOT NULL COMMENT '时间',
  comment TEXT COMMENT '备注',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='子日志表';